### ISSUE TITLE
HTTP status code on invalid input

### ISSUE THREAD

**Issue by Dennis-NavInfo** [ndsev/zswag#109]
I have observed that when the user provides junk input data (wrong payload type, or no payload) that an internal server error code (500) is returned to the user (before userspace code is called). 
I think it would be useful to instead report an http 400 error to show that the error is a user error rather than a server error.

How to reproduce:
- Perform a call to an endpoint in the /ui for which a payload request is expected, but provide none / junk text.
- Observe trace in server, and the status code 500 in the ui.

Desired result:
- Perform a call to an endpoint in the /ui for which a payload request is expected.
- HTTP 400 is returned (stack trace on server might still be useful for debugging, but not desirable in production)

**Comment by josephbirkner** [comment]
Thanks for reporting, and sorry for the delayed response! This seems like a very sensible idea 👍
