### ISSUE TITLE
Allow non-zserio endpoints to be hosted

### ISSUE THREAD

**Issue by Dennis-NavInfo** [ndsev/zswag#93]
In order to support integration with other services I would like to host extra endpoints which are not part of the zserio service itself like /health or /metrics.

Options explored:
- Start another web server which only host the extra endpoints: works but not ideal to not hosting the same api
- Write a custom zserio ServiceInterface: this requires the openApi to be written with zserio encoding, even if zserio is not used
- Invoke add_api directly to host another service: this causes a naming conflict in connexion.

Some experimenting revealed that the issue could be solved by making a small change to https://github.com/ndsev/zswag/blob/v1.4.0/libs/zswag/app.py#L178 where an existing routing controller should be kept if it was explicitly defined in the openapi spec.

Open questions:
- Would it be desirable for OAServer to support this usecase?
- If not: What would the recommended approach be?

**Comment by josephbirkner** [comment]
Hi Dennis, yes, I think your proposed change of respecting an explicitely pre-defined controller would be a good one! Would you like to create a PR? Thanks!
