### ISSUE TITLE
Using the C++ OAClient with your zserio schema.

### ISSUE THREAD

**Issue by kancve** [ndsev/zswag#96]
> The generic C++ client talks to any zserio service that is running via HTTP/REST, and provides an OpenAPI specification of its interface. When using the C++ OAClient with your zserio schema, make sure that the flag -withTypeInfoCode is passed to the zserio C++ emitter.

It should be ensured that the flag -withReflectionCode is passed? Enable reflection code.

**Comment by josephbirkner** [comment]
Thanks for catching this one!
